# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c98e80d7d1693d7814eacb141a2811e05bec496ecc78891c6881e533a0d281c41f25ed44e4b76cd4b5b2d2f0ab7ac48e8693098302805be240e226d573724bfc

test:
  secret_key_base: 465b9b6999a6c7d885211f429c4c360108c910a780181b678569cfebf44796b84143852c096193f3cea40616edb34542556654686130e2a6e6e0dcf6168e4e04

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
